import { chromium } from 'playwright'
const [P, C, tag] = process.argv.slice(2)
const b = await chromium.launch()
const ctx = await b.newContext({ viewport: { width: 1920, height: 1080 } })
await ctx.addInitScript((p) => { localStorage.setItem('atlas.projet', p); localStorage.setItem('atlas.vue','agents') }, P)
const pg = await ctx.newPage()
await pg.goto('http://localhost:5173/')
await pg.waitForTimeout(5000)
await pg.click(`.sessions-liste a[data-id="${C}"]`)
await pg.waitForTimeout(6000)
await pg.screenshot({ path: `capture/explore/${tag}-conv-agents.png` })
await pg.click('.onglets [data-vue=documents]'); await pg.waitForTimeout(3000)
await pg.screenshot({ path: `capture/explore/${tag}-conv-docs.png` })
await b.close()
